config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :members
  root 'welcome#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :donation_date, :donation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<header class="subnav-hero-section">
  <h1 class="subnav-hero-headline">Gajanan Niwas <small>Mitramandal</small></h1>
  <ul class="subnav-hero-subnav">
    <li><%= link_to 'Members', members_path ,class: "is-active"%></li>
    <li><%= link_to 'Login', new_user_session_path %></li>
    <li><a href="#">Take Action!</a></li>
    <li><a href="#" >Carpe Diem!</a></li>
    <li><a target="_blank" href="http://zurb.com/responsive">Just do it!</a></li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/nav'%>
    <div class="row">
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :member_name %>
  </div>

  <div class="field">
    <%= form.label :donation_date %>
    <%= form.date_select :donation_date, id: :member_donation_date %>
  </div>

  <div class="field">
    <%= form.label :donation %>
    <%= form.number_field :donation, id: :member_donation %>
  </div>

  <div class="actions">
    <%= form.submit :class => 'button'%>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Donation date</th>
      <th>Donation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.donation_date %></td>
        <td><%= member.donation %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Donation date:</strong>
  <%= @member.donation_date %>
</p>

<p>
  <strong>Donation:</strong>
  <%= @member.donation %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/welcome/home.html.erb
<!--

<div class="hero-section">
  <div class="hero-section-text">
    <h1>Gajanan Niwas , Mitramandal.</h1>
    <h5></h5>
  </div>
</div>

a-label="FullScreen Pictures" data-orbit>
    <ul class="orbit-container">
      <button class="orbit-previous">
        <span class="show-for-sr">Previous Slide</span>
        <span class="nav fa fa-chevron-left fa-3x"></span>
      </button>
      <button class="orbit-next">
        <span class="show-for-sr">Next Slide</span>
        <span class="nav fa fa-chevron-right fa-3x"></span>
      </button>
      <li class="is-active orbit-slide">
        <img class="orbit-image" src="https://i.imgur.com/16z9ObN.jpg" alt="Space">
        <figcaption class="orbit-caption">
          <h1>Lorem ipsum dolor sit amet, <br>consectetur adipisicing elit.</h1>
        </figcaption>
      </li>
      <li class="orbit-slide">
        <img class="orbit-image" src="https://i.imgur.com/JD4Caxa.jpg" alt="Space">
        <figcaption class="orbit-caption">
          <h1>Lorem ipsum dolor sit amet, <br>consectetur adipisicing elit.</h1>
        </figcaption>
      </li>
      <li class="orbit-slide">
        <img class="orbit-image" src="https://i.imgur.com/rsTQbNV.jpg" alt="Space">
        <figcaption class="orbit-caption">
          <h1>Lorem ipsum dolor sit amet, <br>consectetur adipisicing elit.</h1>
        </figcaption>
      </li>
    </ul>
  </div>
</div>




-->